#!/bin/bash



while getopts "g:n:b:" opt; do
      case $opt in
        g)
          grupa=$OPTARG
          while read -r LINE || [[ -n $LINE ]]; do
            let maxjobs=LINE
            read -r LINE
            let count=LINE
          done < $grupa
          ;;
        n)
          let count=$OPTARG
          ;;
        b)
          let maxjobs=$OPTARG
        ;;
        \?)
          echo "Invalid option: -$OPTARG" >&2
          exit 1
          ;;
        :)
          echo "Option -$OPTARG requires an argument." >&2
          exit 1
          ;;
      esac
done

printf "$maxjobs\n$count" > $grupa